#!/bin/bash

$IPTABLES -A tcp_packets_in -p TCP -d $LAN_IP --dport $SERVICE_PORT_SSH -m state --state $ESTABLISHED -j ACCEPT 
$IPTABLES -A tcp_packets_in -p TCP -d $LAN_IP --dport $SERVICE_PORT_SSH --tcp-flags SYN,RST,ACK SYN -m state --state NEW -j LOG --log-prefix "new SSH connection  " 
$IPTABLES -A tcp_packets_in -p TCP -d $LAN_IP --dport $SERVICE_PORT_SSH --tcp-flags SYN,RST,ACK SYN -m state --state NEW -j ACCEPT


$IPTABLES -A tcp_packets_out -p TCP -s $LAN_IP --sport $SERVICE_PORT_SSH -m state --state $ESTABLISHED -j ACCEPT

