#!/bin/bash

$IPTABLES -A tcp_packets_in -p TCP -d $LAN_IP --sport $PORT_HTTP -m state --state $ESTABLISHED -j ACCEPT  

$IPTABLES -A tcp_packets_out -p TCP -s $LAN_IP --dport $PORT_HTTP -m state --state $ESTABLISHED -j ACCEPT
if [ $HTTP_CONNECTION_LOGGING == true ] ;then
	$IPTABLES -A tcp_packets_out -p TCP -s $LAN_IP --dport $PORT_HTTP --tcp-flags SYN,RST,ACK SYN -m state --state NEW -j LOG --log-prefix "new HTTP connection  "
fi
$IPTABLES -A tcp_packets_out -p TCP -s $LAN_IP --dport $PORT_HTTP --tcp-flags SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
